   name: GitHub Actions Demo
   run-name: ${{ github.actor }} is testing out GitHub Actions 
   on: [push]
   jobs:
     Explore-GitHub-Actions:
       runs-on: ubuntu-latest
       steps:
         - name: Set env as secret
           env:
             REPO_SECRET: ${{ secrets.MY_REPO_SECRET }}
             ORG_SECRET: ${{ secrets.MY_ORG_SECRET }}
           run: |
             import os
             print("---------- REPO SECRET ---------")
             for q in (os.getenv("REPO_SECRET")):
               print(q)
   
             print("---------- ORG SECRET ---------")
             for o in (os.getenv("ORG_SECRET")):
               print(o)
           shell: python
