name: GitHub Actions Demo  
run-name: ${{ github.actor }} is testing out GitHub Actions   
on: [push]  
jobs:  
  Explore-GitHub-Actions:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Set env as secret  
        run: |
          echo ${{ secrets.MY_REPO_SECRET }}  
      echo ${{ secrets.MY_ORG_SECRET }}
